[theme]
base                     = "dark"
primaryColor             = "#F4A623"
backgroundColor          = "#0d0d0d"
secondaryBackgroundColor = "#1a1a1a"
textColor                = "#f0f0f0"
font                     = "sans serif"

[client]
showSidebarNavigation = false